/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => AutoSidebarPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var HOVER_ZONE_PX = 8;
var HIDE_DELAY_MS = 150;
var DOC_LEAVE_DELAY_MS = 1e3;
var AutoSidebarPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.leftCompact = false;
    this.leftWidth = 270;
    /** Disabled — sidebar stays permanently collapsed/unexpandable */
    this.leftDisabled = false;
    this.listenerActive = false;
    this.hideTimer = null;
    this.leaveTimer = null;
    /** Obsidian's inline `width` before we overwrite it for overlay. */
    this.obsidianWidth = "";
    /* ================================================================
       HOVER DETECTION
       ================================================================ */
    /** Mouse left Obsidian's window entirely — start delayed hide. */
    this.onDocumentLeave = () => {
      if (!this.leftCompact)
        return;
      const el = this.splitEl();
      if (!(el == null ? void 0 : el.classList.contains("auto-sidebar-visible")))
        return;
      if (this.leaveTimer !== null)
        return;
      this.leaveTimer = setTimeout(() => {
        this.concealOverlay();
        this.leaveTimer = null;
      }, DOC_LEAVE_DELAY_MS);
    };
    /** Mouse re-entered the window — cancel pending hide. */
    this.onDocumentEnter = () => {
      if (this.leaveTimer !== null) {
        clearTimeout(this.leaveTimer);
        this.leaveTimer = null;
      }
    };
    /** Window lost focus (Alt+Tab, Win+Tab, Cmd+`) — trigger delayed hide. */
    this.onWindowBlur = () => {
      this.onDocumentLeave();
    };
    this.onMouseMove = (e) => {
      if (this.leftCompact)
        this.edgeCheck(e.clientX, e.clientY);
    };
  }
  /* ================================================================
     LIFECYCLE
     ================================================================ */
  async onload() {
    var _a, _b, _c;
    const data = await this.loadData();
    if (data) {
      this.leftCompact = (_a = data.leftCompact) != null ? _a : false;
      this.leftWidth = (_b = data.leftWidth) != null ? _b : 270;
      this.leftDisabled = (_c = data.leftDisabled) != null ? _c : false;
    }
    this.addSettingTab(new AutoSidebarSettingTab(this.app, this));
    this.addCommand({
      id: "toggle-left-compact",
      name: "Toggle compact mode",
      callback: () => this.toggle()
    });
    this.app.workspace.onLayoutReady(() => {
      if (!this.leftDisabled && this.leftCompact) {
        const split = this.splitAPI();
        if (split) {
          split.expand();
          requestAnimationFrame(() => {
            const el = this.splitEl();
            if (!el)
              return;
            this.obsidianWidth = el.style.width || "";
            el.style.setProperty("width", this.leftWidth + "px", "important");
            el.classList.add("auto-sidebar-compact");
            this.leftCompact = true;
            this.syncListener();
            this.persist();
          });
        }
      }
      if (this.leftDisabled) {
        const split = this.splitAPI();
        if (split && !split.collapsed)
          split.collapse();
      }
    });
  }
  onunload() {
    this.cleanupSide();
    this.teardownListeners();
  }
  /* ================================================================
     TOGGLE
     ================================================================ */
  toggle() {
    if (this.leftDisabled)
      return;
    if (this.leftCompact) {
      this.uncompact();
    } else {
      this.enterCompact();
    }
  }
  /* ================================================================
     ENTER COMPACT MODE  (NCM → CM)
     ================================================================ */
  enterCompact() {
    if (this.leftDisabled)
      return;
    const split = this.splitAPI();
    if (!split)
      return;
    split.expand();
    requestAnimationFrame(() => {
      const el = this.splitEl();
      if (!el)
        return;
      const w = el.getBoundingClientRect().width;
      if (w <= 10) {
        this.leftCompact = false;
        this.persist();
        return;
      }
      this.leftWidth = w;
      this.obsidianWidth = el.style.width || "";
      el.style.setProperty("width", w + "px", "important");
      el.classList.add("auto-sidebar-compact");
      this.leftCompact = true;
      this.syncListener();
      this.persist();
    });
  }
  /* ================================================================
     EXIT COMPACT MODE  (CM → NCM)
     ================================================================ */
  uncompact() {
    const el = this.splitEl();
    if (!el)
      return;
    const split = this.splitAPI();
    const w = this.leftWidth;
    el.classList.remove(
      "auto-sidebar-compact",
      "auto-sidebar-visible"
    );
    split == null ? void 0 : split.expand();
    el.style.removeProperty("width");
    if (this.obsidianWidth) {
      el.style.width = this.obsidianWidth;
    } else {
      el.style.width = w + "px";
    }
    this.leftCompact = false;
    this.persist();
    this.syncListener();
  }
  /* ================================================================
     OVERLAY SHOW / HIDE  (CM only, hover-triggered, no animation)
     ================================================================ */
  revealOverlay() {
    const el = this.splitEl();
    if (!el || el.classList.contains("auto-sidebar-visible"))
      return;
    const split = this.splitAPI();
    if (split == null ? void 0 : split.collapsed)
      split.expand();
    el.style.setProperty("width", this.leftWidth + "px", "important");
    el.classList.add("auto-sidebar-visible");
  }
  concealOverlay() {
    const el = this.splitEl();
    if (!el || !el.classList.contains("auto-sidebar-visible"))
      return;
    el.classList.remove("auto-sidebar-visible");
  }
  edgeCheck(x, y) {
    if (this.leftDisabled)
      return;
    const el = this.splitEl();
    if (!el)
      return;
    const showing = el.classList.contains("auto-sidebar-visible");
    const nearEdge = x <= HOVER_ZONE_PX;
    if (nearEdge && !showing) {
      this.clearTimer();
      this.revealOverlay();
      return;
    }
    if (!showing)
      return;
    if (this.pointerIn(el, x, y)) {
      this.clearTimer();
    } else if (!nearEdge) {
      this.startTimer();
    }
  }
  pointerIn(el, x, y) {
    const r = el.getBoundingClientRect();
    return x >= r.left && x <= r.right && y >= r.top && y <= r.bottom;
  }
  startTimer() {
    if (this.hideTimer !== null)
      return;
    this.hideTimer = setTimeout(() => {
      this.concealOverlay();
      this.hideTimer = null;
    }, HIDE_DELAY_MS);
  }
  clearTimer() {
    if (this.hideTimer !== null) {
      clearTimeout(this.hideTimer);
      this.hideTimer = null;
    }
    if (this.leaveTimer !== null) {
      clearTimeout(this.leaveTimer);
      this.leaveTimer = null;
    }
  }
  syncListener() {
    if (this.leftCompact && !this.listenerActive) {
      document.addEventListener("mousemove", this.onMouseMove);
      document.documentElement.addEventListener("mouseleave", this.onDocumentLeave);
      document.documentElement.addEventListener("mouseenter", this.onDocumentEnter);
      window.addEventListener("blur", this.onWindowBlur);
      this.listenerActive = true;
    } else if (!this.leftCompact && this.listenerActive) {
      document.removeEventListener("mousemove", this.onMouseMove);
      document.documentElement.removeEventListener("mouseleave", this.onDocumentLeave);
      document.documentElement.removeEventListener("mouseenter", this.onDocumentEnter);
      window.removeEventListener("blur", this.onWindowBlur);
      this.listenerActive = false;
    }
  }
  teardownListeners() {
    if (!this.listenerActive)
      return;
    document.removeEventListener("mousemove", this.onMouseMove);
    document.documentElement.removeEventListener("mouseleave", this.onDocumentLeave);
    document.documentElement.removeEventListener("mouseenter", this.onDocumentEnter);
    window.removeEventListener("blur", this.onWindowBlur);
    this.listenerActive = false;
  }
  /* ================================================================
     PERSISTENCE
     ================================================================ */
  persist() {
    this.saveData({
      leftCompact: this.leftCompact,
      leftWidth: this.leftWidth,
      leftDisabled: this.leftDisabled
    });
  }
  /* ================================================================
     HELPERS
     ================================================================ */
  splitAPI() {
    return this.app.workspace.leftSplit;
  }
  splitEl() {
    var _a, _b;
    return (_b = (_a = this.splitAPI()) == null ? void 0 : _a.containerEl) != null ? _b : null;
  }
  /** Enable/disable the sidebar.  When enabling disable, the sidebar is
   *  exited from CM (if active) and collapsed via the Obsidian API.  When
   *  disabling disable, the sidebar is expanded again. */
  setDisabled(value) {
    this.leftDisabled = value;
    if (value) {
      if (this.leftCompact) {
        this.cleanupSide();
        this.leftCompact = false;
      }
      const split = this.splitAPI();
      if (split && !split.collapsed) {
        split.collapse();
      }
      this.syncListener();
    } else {
      const split = this.splitAPI();
      if (split && split.collapsed) {
        split.expand();
      }
    }
    this.persist();
  }
  cleanupSide() {
    const el = this.splitEl();
    if (!el)
      return;
    const split = this.splitAPI();
    if (split == null ? void 0 : split.collapsed)
      split.expand();
    el.classList.remove(
      "auto-sidebar-compact",
      "auto-sidebar-visible"
    );
    el.style.removeProperty("width");
    if (this.obsidianWidth) {
      el.style.width = this.obsidianWidth;
    }
    el.style.removeProperty("flex-basis");
    el.style.removeProperty("min-width");
    el.style.removeProperty("transition");
    el.style.overflow = "";
  }
};
var AutoSidebarSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Disable sidebar").setDesc(
      "Keep left sidebar permanently collapsed. Keyboard shortcuts, hover, and CM transitions will not expand it."
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin["leftDisabled"]).onChange((value) => {
        this.plugin.setDisabled(value);
      })
    );
  }
};
