/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => AutoSidebarPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var HOVER_ZONE_PX = 8;
var HIDE_DELAY_MS = 400;
var AutoSidebarPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.leftCompact = false;
    this.rightCompact = false;
    this.leftWidth = 270;
    this.rightWidth = 270;
    this.listenerActive = false;
    this.hideTimers = {
      left: null,
      right: null
    };
    /* ================================================================
       HOVER DETECTION
       ================================================================ */
    this.onMouseMove = (e) => {
      const x = e.clientX;
      if (this.leftCompact)
        this.edgeCheck("left", x, e.clientY);
      if (this.rightCompact)
        this.edgeCheck("right", x, e.clientY);
    };
  }
  /* ================================================================
     LIFECYCLE
     ================================================================ */
  async onload() {
    var _a, _b, _c, _d;
    const data = await this.loadData();
    if (data) {
      this.leftCompact = (_a = data.leftCompact) != null ? _a : false;
      this.rightCompact = (_b = data.rightCompact) != null ? _b : false;
      this.leftWidth = (_c = data.leftWidth) != null ? _c : 270;
      this.rightWidth = (_d = data.rightWidth) != null ? _d : 270;
    }
    this.addCommand({
      id: "toggle-left-compact",
      name: "Toggle left compact mode",
      callback: () => this.toggle("left")
    });
    this.addCommand({
      id: "toggle-right-compact",
      name: "Toggle right compact mode",
      callback: () => this.toggle("right")
    });
    this.app.workspace.onLayoutReady(() => {
      if (this.leftCompact)
        this.doCompact("left");
      if (this.rightCompact)
        this.doCompact("right");
    });
  }
  onunload() {
    this.cleanupSide("left");
    this.cleanupSide("right");
    this.syncListener();
  }
  /* ================================================================
     TOGGLE
     ================================================================ */
  toggle(side) {
    const compact = this.compactState(side);
    if (compact) {
      this.uncompact(side);
    } else {
      this.doCompact(side);
    }
  }
  /* ================================================================
     ENTER / EXIT COMPACT MODE
     ================================================================ */
  doCompact(side) {
    const split = this.splitAPI(side);
    if (!split)
      return;
    split.expand();
    requestAnimationFrame(() => {
      const el = this.splitEl(side);
      if (!el)
        return;
      const w = el.getBoundingClientRect().width;
      if (w > 10)
        this.setWidth(side, w);
      this.hide(el);
      this.setCompact(side, true);
      this.syncListener();
      this.persist();
    });
  }
  uncompact(side) {
    const el = this.splitEl(side);
    if (el) {
      el.classList.remove("auto-sidebar-overlay");
      this.show(el);
    }
    this.setCompact(side, false);
    this.syncListener();
    this.persist();
  }
  /* ================================================================
     OVERLAY SHOW / HIDE (compact-mode only)
     ================================================================ */
  revealOverlay(side) {
    const el = this.splitEl(side);
    if (!el || el.classList.contains("auto-sidebar-overlay"))
      return;
    const split = this.splitAPI(side);
    if (split == null ? void 0 : split.collapsed)
      split.expand();
    el.style.removeProperty("flex-basis");
    el.style.removeProperty("min-width");
    el.style.overflow = "";
    el.classList.add("auto-sidebar-overlay");
    const w = this.widthOf(side);
    el.style.setProperty("width", w + "px", "important");
  }
  concealOverlay(side) {
    const el = this.splitEl(side);
    if (!el || !el.classList.contains("auto-sidebar-overlay"))
      return;
    el.classList.remove("auto-sidebar-overlay");
    this.hide(el);
  }
  edgeCheck(side, x, y) {
    const el = this.splitEl(side);
    if (!el)
      return;
    const showing = el.classList.contains("auto-sidebar-overlay");
    const nearEdge = side === "left" ? x <= HOVER_ZONE_PX : x >= window.innerWidth - HOVER_ZONE_PX;
    if (nearEdge && !showing) {
      this.clearTimer(side);
      this.revealOverlay(side);
      return;
    }
    if (!showing)
      return;
    if (this.pointerIn(el, x, y)) {
      this.clearTimer(side);
    } else if (!nearEdge) {
      this.startTimer(side);
    }
  }
  pointerIn(el, x, y) {
    const r = el.getBoundingClientRect();
    return x >= r.left && x <= r.right && y >= r.top && y <= r.bottom;
  }
  startTimer(side) {
    if (this.hideTimers[side] !== null)
      return;
    this.hideTimers[side] = setTimeout(() => {
      this.concealOverlay(side);
      this.hideTimers[side] = null;
    }, HIDE_DELAY_MS);
  }
  clearTimer(side) {
    if (this.hideTimers[side] !== null) {
      clearTimeout(this.hideTimers[side]);
      this.hideTimers[side] = null;
    }
  }
  syncListener() {
    const should = this.leftCompact || this.rightCompact;
    if (should && !this.listenerActive) {
      document.addEventListener("mousemove", this.onMouseMove);
      this.listenerActive = true;
    } else if (!should && this.listenerActive) {
      document.removeEventListener("mousemove", this.onMouseMove);
      this.listenerActive = false;
    }
  }
  /* ================================================================
     STYLE HELPERS
     ================================================================ */
  /** Hide the sidebar — only flex-basis & min-width, never touch width.
   *  Obsidian's resize handle sets `width` via setSize() internally.
   *  In flex row layout, flex-basis overrides width, so setting
   *  flex-basis to 0 is enough to collapse it while preserving the
   *  original width value for NCM restore. */
  hide(el) {
    el.style.setProperty("flex-basis", "0px", "important");
    el.style.setProperty("min-width", "0px", "important");
    el.style.overflow = "hidden";
  }
  /** Restore the sidebar to NCM — remove our overrides, let Obsidian's
   *  inline width (from setSize) apply naturally. */
  show(el) {
    el.style.removeProperty("flex-basis");
    el.style.removeProperty("min-width");
    el.style.overflow = "";
  }
  /* ================================================================
     PERSISTENCE
     ================================================================ */
  persist() {
    this.saveData({
      leftCompact: this.leftCompact,
      rightCompact: this.rightCompact,
      leftWidth: this.leftWidth,
      rightWidth: this.rightWidth
    });
  }
  /* ================================================================
     HELPERS
     ================================================================ */
  splitAPI(side) {
    return side === "left" ? this.app.workspace.leftSplit : this.app.workspace.rightSplit;
  }
  splitEl(side) {
    return document.querySelector(
      side === "left" ? ".workspace-split.mod-left-split" : ".workspace-split.mod-right-split"
    );
  }
  widthOf(side) {
    return side === "left" ? this.leftWidth : this.rightWidth;
  }
  setWidth(side, w) {
    if (side === "left")
      this.leftWidth = w;
    else
      this.rightWidth = w;
  }
  compactState(side) {
    return side === "left" ? this.leftCompact : this.rightCompact;
  }
  setCompact(side, v) {
    if (side === "left")
      this.leftCompact = v;
    else
      this.rightCompact = v;
  }
  cleanupSide(side) {
    const el = this.splitEl(side);
    if (!el)
      return;
    el.classList.remove("auto-sidebar-overlay");
    el.style.removeProperty("width");
    el.style.removeProperty("flex-basis");
    el.style.removeProperty("min-width");
    el.style.overflow = "";
  }
};
